layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: yemreak
  # mastodon: your_username
  medium: yedhrab
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://yemreak.com
  # youtube: your_username

topics:
  - name: Kütüphane
    web_url: https://lib.yemreak.com
    image_url: https://blobscdn.gitbook.com/v0/b/gitbook-28427.appspot.com/o/spaces%2F-LrcGwDVnghIgjDIIhGv%2Favatar.png?generation=1577452653033446&alt=media
  
  - name: Python
    web_url: https://python.yemreak.com
    image_url: https://blobscdn.gitbook.com/v0/b/gitbook-28427.appspot.com/o/spaces%2F-LtB5G30DaqfA7nrlh-D%2Favatar.png?generation=1573290950010225&alt=media
  
  - name: Öğrenme Yolları
    web_url: https://learn.yemreak.com
    image_url: https://blobscdn.gitbook.com/v0/b/gitbook-28427.appspot.com/o/spaces%2F-LrZB99YEYKrL-joiloa%2Favatar.png?generation=1576226073603386&alt=media
  
  - name: AI
  - name: Android
  - name: Linux
  - name: Java
  - name: Productivity
